# Generated by Django 4.2 on 2024-10-27 17:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conferences_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferences',
            options={'verbose_name_plural': 'Conferences'},
        ),
        migrations.AlterField(
            model_name='conferences',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=900, message='capacity must be under 900')]),
        ),
        migrations.AlterField(
            model_name='conferences',
            name='program',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'], message='only pdf png jpg jpeg are allowed')]),
        ),
        migrations.AlterField(
            model_name='conferences',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 10, 27)),
        ),
        migrations.AddConstraint(
            model_name='conferences',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2024, 10, 27))), name='the start date must be greater than today or equal'),
        ),
    ]
