# Generated by Django 4.2 on 2024-10-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_alter_conferences_options_alter_conferences_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferences',
            options={},
        ),
    ]
